name:                haskysack
version:             0.1.0.0
github:              "githubuser/haskysack"
license:             MIT
author:              "Sebastian Sangervasi"
maintainer:          "sorrymyemailaddressisverylong@gmail.com"
copyright:           "2018 Sebastian Sangervasi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskysack#readme>

dependencies:
- base >= 4.7 && < 5
- strings

library:
  source-dirs: src

executables:
  haskysack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskysack

tests:
  haskysack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskysack
    - hspec
